# Generated by Django 6.1 on 2026-08-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0003_permanence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='type_activite',
            field=models.CharField(choices=[('garde', 'Garde'), ('permanence', 'Permanence'), ('astreinte', 'Astreinte')], default='garde', max_length=15),
        ),
        migrations.AlterField(
            model_name='poste',
            name='type_activite',
            field=models.CharField(choices=[('garde', 'Garde'), ('permanence', 'Permanence'), ('astreinte', 'Astreinte')], default='garde', max_length=15),
        ),
    ]
