# Generated by Django 6.1 on 2026-08-09 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('statut', models.CharField(default='brouillon', max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='referentiels.service')),
            ],
            options={
                'unique_together': {('service', 'annee', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='Garde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referentiels.poste')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardes', to='plannings.planning')),
            ],
            options={
                'unique_together': {('planning', 'poste', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AffectationGarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('garde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='plannings.garde')),
            ],
            options={
                'unique_together': {('garde', 'agent')},
            },
        ),
    ]
