# Generated by Django 6.1 on 2026-08-10 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannings', '0001_initial'),
        ('referentiels', '0002_equipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_suivant', models.IntegerField(default=0)),
                ('poste', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etat_rotation', to='referentiels.poste')),
            ],
        ),
    ]
