# Generated by Django 6.1 on 2026-08-19 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannings', '0003_planning_type_activite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EtatRotation',
        ),
    ]
