# Generated by Django 6.1 on 2026-08-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannings', '0004_delete_etatrotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationgarde',
            name='heures',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
