# Generated by Django 6.1 on 2026-08-09 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur_email', models.CharField(blank=True, max_length=120)),
                ('action', models.CharField(max_length=255)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('heures_ouvrable', models.FloatField(default=0)),
                ('heures_vendredi', models.FloatField(default=0)),
                ('heures_ramadan', models.FloatField(default=0)),
                ('heures_weekend_ferie', models.FloatField(default=0)),
                ('heures_nuit', models.FloatField(default=0)),
                ('total_heures', models.FloatField(default=0)),
                ('statut_validation', models.CharField(default='prepare', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decomptes', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referentiels.service')),
            ],
            options={
                'unique_together': {('agent', 'annee', 'mois', 'service')},
            },
        ),
    ]
