# Generated by Django 6.1 on 2026-08-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decomptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalaudit',
            options={'ordering': ['-horodatage']},
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='cible',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
