# Generated by Django 6.1 on 2026-08-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bareme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vacation', models.CharField(max_length=10)),
                ('categorie_jour', models.CharField(max_length=20)),
                ('heures', models.FloatField()),
                ('date_effet', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('libelle', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodeRamadan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
    ]
