# Generated by Django 6.1 on 2026-08-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='fonction',
            field=models.CharField(blank=True, choices=[('medecin', 'Médecin'), ('infirmier', 'Infirmier'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
    ]
